export enum Role {
  CUSTOMER = 'CUSTOMER',
  ADMIN = 'ADMIN',
}

export enum OrderStatus {
  PENDING_PAYMENT = 'PENDING_PAYMENT',
  PAID = 'PAID',
  PROCESSING = 'PROCESSING',
  SHIPPED = 'SHIPPED',
  DELIVERED = 'DELIVERED',
  CANCELLED = 'CANCELLED',
  REFUNDED = 'REFUNDED',
}

export enum PaymentStatus {
  PENDING = 'PENDING',
  COMPLETED = 'COMPLETED',
  FAILED = 'FAILED',
  REFUNDED = 'REFUNDED',
}

export enum ShipmentStatus {
  LABEL_PENDING = 'LABEL_PENDING',
  LABEL_GENERATED = 'LABEL_GENERATED',
  IN_TRANSIT = 'IN_TRANSIT',
  DELIVERED = 'DELIVERED',
  FAILED = 'FAILED',
  RETURNED = 'RETURNED',
}

export enum CarrierCode {
  INPOST = 'INPOST',
  DHL = 'DHL',
  GLS = 'GLS',
}

export enum DiscountType {
  PERCENTAGE = 'PERCENTAGE',
  FIXED_AMOUNT = 'FIXED_AMOUNT',
  FREE_SHIPPING = 'FREE_SHIPPING',
}

export enum CouponType {
  WELCOME = 'WELCOME',
  BIRTHDAY = 'BIRTHDAY',
  CART_ABANDONMENT = 'CART_ABANDONMENT',
  LOYALTY = 'LOYALTY',
  WIN_BACK = 'WIN_BACK',
  SUBSCRIPTION = 'SUBSCRIPTION',
  CUSTOM = 'CUSTOM',
}
