export enum Role {
  CUSTOMER = 'CUSTOMER',
  ADMIN = 'ADMIN',
}

export enum OrderStatus {
  PENDING_PAYMENT = 'PENDING_PAYMENT',
  FRAUD_REVIEW = 'FRAUD_REVIEW',
  PAID = 'PAID',
  PROCESSING = 'PROCESSING',
  SHIPPED = 'SHIPPED',
  DELIVERED = 'DELIVERED',
  CANCELLED = 'CANCELLED',
  REFUNDED = 'REFUNDED',
  PARTIALLY_REFUNDED = 'PARTIALLY_REFUNDED',
  DISPUTE_HOLD = 'DISPUTE_HOLD',
}

export enum PaymentStatus {
  PENDING = 'PENDING',
  COMPLETED = 'COMPLETED',
  FAILED = 'FAILED',
  REFUNDED = 'REFUNDED',
}

export enum ShipmentStatus {
  LABEL_PENDING = 'LABEL_PENDING',
  LABEL_GENERATED = 'LABEL_GENERATED',
  LABEL_ERROR = 'LABEL_ERROR',
  IN_TRANSIT = 'IN_TRANSIT',
  DELIVERED = 'DELIVERED',
  FAILED = 'FAILED',
  RETURNED = 'RETURNED',
}

export enum CarrierCode {
  INPOST = 'INPOST',
  DHL = 'DHL',
  GLS = 'GLS',
  DPD = 'DPD',
  DPD_COURIER = 'DPD_COURIER',
}

export enum DiscountType {
  PERCENTAGE = 'PERCENTAGE',
  FIXED_AMOUNT = 'FIXED_AMOUNT',
  FREE_SHIPPING = 'FREE_SHIPPING',
}

export enum CouponType {
  WELCOME = 'WELCOME',
  BIRTHDAY = 'BIRTHDAY',
  CART_ABANDONMENT = 'CART_ABANDONMENT',
  LOYALTY = 'LOYALTY',
  WIN_BACK = 'WIN_BACK',
  SUBSCRIPTION = 'SUBSCRIPTION',
  CUSTOM = 'CUSTOM',
}

export enum ReviewStatus {
  PENDING = 'PENDING',
  APPROVED = 'APPROVED',
  REJECTED = 'REJECTED',
}

export enum ReturnType {
  WITHDRAWAL = 'WITHDRAWAL',
  COMPLAINT = 'COMPLAINT',
}

export enum ReturnStatus {
  PENDING = 'PENDING',
  IN_REVIEW = 'IN_REVIEW',
  APPROVED = 'APPROVED',
  REJECTED = 'REJECTED',
  COMPLETED = 'COMPLETED',
}

export enum ProductStatus {
  ACTIVE = 'ACTIVE',
  OUT_OF_STOCK = 'OUT_OF_STOCK',
  DISCONTINUED = 'DISCONTINUED',
  COMING_SOON = 'COMING_SOON',
}
