/**
 * One-time script — populates ingredients, warnings, paoMonths on every perfume product
 * and uploads SDS PDFs to Supabase Storage, then sets sdsUrl on diffuser products.
 *
 * Run: npx ts-node -P tsconfig.json prisma/update-compliance.ts
 */

import { PrismaClient } from '@prisma/client';
import { createClient } from '@supabase/supabase-js';
import * as fs from 'fs';
import * as path from 'path';
import * as dotenv from 'dotenv';

dotenv.config({ path: path.join(__dirname, '../.env') });

const prisma = new PrismaClient();
const supabase = createClient(
  process.env.SUPABASE_URL!,
  process.env.SUPABASE_SERVICE_ROLE_KEY!,
);

const DOCS_DIR = path.join(__dirname, '../../../docs');
const SDS_BUCKET = 'product-images';

// ─── INCI/warnings/PAO data keyed by base_code (= primary variant SKU) ──────

interface ComplianceEntry {
  inci: string;
  warnings: string;
  paoMonths: number;
}

const W1 = 'Nie spryskiwać na otwarty ogień ani rozgrzane powierzchnie; Unikać kontaktu z oczami; Przechowywać w miejscu niedostępnym dla dzieci';
const W2 = 'Nie spryskiwać na otwarty ogień ani inne źródła zapłonu; Unikać kontaktu z oczami; Przechowywać w miejscu niedostępnym dla dzieci';
const W3 = 'Nie spryskiwać na otwarty ogień ani gorące powierzchnie; Unikać kontaktu z oczami; Przechowywać w miejscu niedostępnym dla dzieci';

const COMPLIANCE: Record<string, ComplianceEntry> = {
  '080W': { paoMonths: 36, warnings: W1, inci: 'Alcohol denat., Parfum, Hexamethylindanopyran, Benzyl benzoate, Tetramethyl acetyloctahydronaphthalenes, Linalyl acetate, Benzyl alcohol, Linalool, Hydroxycitronellal, Citrus limon peel oil, Vanillin, Limonene, Pogostemon cablin leaf oil, Hexyl cinnamal, Geraniol, Cinnamyl alcohol, Pinene, Alpha-isomethyl ionone, Citronellol, Phenethyl dimethyl acetate, Geranyl acetate, Citral, Rose ketones, Beta-caryophyllene, Eugenol, Cinnamal' },
  '038M': { paoMonths: 36, warnings: W1, inci: 'Alcohol denat., Parfum, Tetramethyl acetyloctahydronaphthalenes, Limonene, Citrus limon peel oil, Hexamethylindanopyran, Linalyl acetate, Citrus aurantium peel oil, Pogostemon cablin oil, Linalool, Citronellol, Acetylcedrene, Citral, Coumarin, Anethole, Beta-caryophyllene, Terpineol, Mentha piperita oil, Geranyl acetate, Pelargonium graveolens flower oil, Rose ketones, Geraniol, Terpinolene, Alpha terpinene, Menthol, Benzyl benzoate, Trimethylcyclopentenyl methylisopentenol' },
  '006W': { paoMonths: 36, warnings: W1, inci: 'Alcohol denat., Parfum, Benzyl salicylate, Pogostemon cablin oil, Acetylcedrene, Hydroxycitronellal, Limonene, Linalyl acetate, Eugenol, Linalool, Dimethylbenzyl carbinyl acetate, Geranyl acetate, Hexamethylindanopyran, Hexyl cinnamal, Citrus limon peel oil, Pinene, Benzyl benzoate, Citrus aurantium peel oil, Geraniol, Evernia prunastri extract, Citronellol, Eugenyl acetate, Beta-caryophyllene, Citral, Benzyl alcohol, Evernia furfuracea extract, Benzyl cinnamate, Vanillin, Terpineol, Cinnamyl alcohol, Alpha-terpinene, Benzaldehyde, Terpinolene, Isoeugenyl acetate' },
  '157M': { paoMonths: 36, warnings: W1, inci: 'Alcohol denat., Parfum, Tetramethyl acetyloctahydronaphthalenes, Linalyl acetate, Limonene, Citrus limon peel oil, Linalool, Hydroxycitronellal, Pogostemon cablin oil, Citrus aurantium peel oil, Vanillin, Juniperus virginiana oil, Hexamethylindanopyran, Pinene, Amyl salicylate, Coumarin, Lavandula oil / extract, Citronellol, Citral, Beta-caryophyllene, Rose ketones, Sclareol, Carvone, Terpineol, Mentha viridis oil, Camphor, Geraniol, Terpinolene, Geranyl acetate, Alpha-terpinene' },
  '081W': { paoMonths: 36, warnings: W1, inci: 'Alcohol denat., Parfum, Tetramethyl acetyloctahydronaphthalenes, Hexamethylindanopyran, Benzyl salicylate, Hydroxycitronellal, Linalool, Hexyl cinnamal, Limonene, Vanillin, Alpha-isomethyl ionone, Acetylcedrene, Linalyl acetate, Citronellol, Coumarin, Geraniol, Citrus aurantium peel oil, Pinene, Rose ketones, Citral, Geranyl acetate, Beta-caryophyllene, Terpineol, Benzyl benzoate, Benzyl alcohol, Rose flower oil / extract, Isoeugenyl acetate, Farnesol, Benzyl cinnamate' },
  '011W': { paoMonths: 36, warnings: W3, inci: 'Alcohol denat., Parfum, Tetramethyl acetyloctahydronaphthalenes, Citrus limon peel oil, Hexamethylindanopyran, Limonene, Pinene, Juniperus virginiana oil, Cedrus atlantica extract, Citral, Geranyl acetate, Rose ketones, Beta-caryophyllene, Cinnamal, Linalool, Geraniol, Dimethylbenzyl carbinyl acetate' },
  '052A': { paoMonths: 36, warnings: W2, inci: 'Alcohol denat., Parfum, Tetramethyl acetyloctahydronaphthalenes, Hexamethylindanopyran, Pogostemon cablin oil, Linalool, Linalyl acetate, Eugenol, Hexyl cinnamal, Pinene, Citrus limon peel oil, Coumarin, Limonene, Lavandula oil / extract, Beta-caryophyllene, Citronellol, Eucalyptus globulus oil, Camphor, Citral, Alpha-terpinene, Terpineol, Rose ketones, Geraniol, Terpinolene, Geranyl acetate, Isoeugenol, Acetylcedrene' },
  '055W': { paoMonths: 36, warnings: W1, inci: 'Alcohol denat., Parfum, Tetramethyl acetyloctahydronaphthalenes, Benzyl salicylate, Hexamethylindanopyran, Linalool, Linalyl acetate, Vanillin, Hydroxycitronellal, Hexyl cinnamal, Limonene, Dimethyl phenethyl acetate, Geranyl acetate, Juniperus virginiana oil, Citronellol, Geraniol, Pogostemon cablin oil, Cinnamyl alcohol, Rose ketones, Pinene, Beta-caryophyllene, Benzyl alcohol, Citral, Benzyl benzoate' },
  '163W': { paoMonths: 36, warnings: 'Nie spryskiwać w kierunku otwartego ognia ani na rozgrzane powierzchnie; Unikać kontaktu z oczami; Przechowywać w miejscu niedostępnym dla dzieci', inci: 'Alcohol denat., Parfum, Tetramethyl acetyloctahydronaphthalenes, Alpha-isomethyl ionone, Linalool, Geraniol, Hydroxycitronellal, Geranyl acetate, Linalyl acetate, Pogostemon cablin oil, Hexyl cinnamal, Limonene, Citrus aurantium peel oil, Coumarin, Citrus aurantium bergamia peel oil, Hexadecanolactone, Rose ketones, Beta-caryophyllene, Pinene, Citronellol, Citral' },
  '042W': { paoMonths: 36, warnings: 'Nie spryskiwać na otwarty ogień ani inne źródła zapłonu; Unikać kontaktu z oczami; Trzymać z dala od dzieci', inci: 'Alcohol denat., Parfum, Linalyl acetate, Linalool, Benzyl salicylate, Tetramethyl acetyloctahydronaphthalenes, Hexamethylindanopyran, Alpha-isomethyl ionone, Limonene, Citronellol, Citrus aurantium peel oil, Coumarin, Pinene, Rose ketones, Beta-caryophyllene, Geraniol, Terpineol, Benzyl alcohol, Citral, Benzyl benzoate, Acetylcedrene, Terpinolene' },
  '159W': { paoMonths: 36, warnings: W1, inci: 'Alcohol denat., Parfum, Tetramethyl acetyloctahydronaphthalenes, Hexamethylindanopyran, Citrus aurantium bergamia peel oil, Limonene, Vanillin, Linalyl acetate, Citrus aurantium peel oil, Linalool, Pinene, Citronellol, Rose ketones, Citral, Terpinolene, Terpineol, Geranyl acetate' },
  '160M': { paoMonths: 36, warnings: W1, inci: 'Alcohol denat., Parfum, Trimethylbenzenepropanol, Lippia citriodora absolute, Linalool, Cymbopogon schoenanthus oil, Methyl 2-octynoate, Linalyl acetate, Eugenol, Citrus limon peel oil, Coumarin, Terpineol, Pinene, Hexyl cinnamal, Salicylaldehyde, Cananga odorata flower oil, Limonene, Citronellol, Camphor, Tetramethyl acetyloctahydronaphthalenes, Amyl salicylate' },
  '131W': { paoMonths: 36, warnings: W1, inci: 'Alcohol denat., Parfum, Tetramethyl acetyloctahydronaphthalenes, Hexamethylindanopyran, Linalool, Benzyl salicylate, Vanillin, Linalyl acetate, Hydroxycitronellal, Coumarin, Benzyl benzoate, Citrus limon peel oil, Limonene, Trimethylcyclopentenyl methylisopentenol, Pinene, Juniperus virginiana oil, Geraniol, Rose ketones, Trimethylbenzenepropanol, Beta-caryophyllene, Benzaldehyde, Citral, Terpinolene, Dimethyl phenethyl acetate, Citronellol, Benzyl alcohol, Geranyl acetate, Terpineol, Alpha-terpinene' },
  '140M': { paoMonths: 36, warnings: W1, inci: 'Alcohol denat., Parfum, Tetramethyl acetyloctahydronaphthalenes, Citrus limon peel oil, Linalyl acetate, Limonene, Hexamethylindanopyran, Vanillin, Linalool, Pinene, Coumarin, Alpha-isomethyl ionone, Citronellol, Juniperus virginiana oil, Carvone, Rose ketones, Cedrus atlantica wood oil, Citral, Beta-caryophyllene, Pelargonium graveolens flower oil, Mentha piperita oil, Cinnamomum zeylanicum bark oil, Terpinolene, Geraniol, Menthol, Cinnamal, Terpineol, Geranyl acetate, Alpha-terpinene' },
  '119W': { paoMonths: 36, warnings: W1, inci: 'Alcohol denat., Parfum, Tetramethyl acetyloctahydronaphthalenes, Benzyl salicylate, Hexamethylindanopyran, Linalyl acetate, Limonene, Vanillin, Pogostemon cablin oil, Citrus aurantium peel oil, Linalool, Citrus limon peel oil, Coumarin, Alpha-isomethyl ionone, Pinene, Rose ketones, Beta-caryophyllene, Cananga odorata oil / extract, Citral, Benzaldehyde, Benzyl benzoate, Geraniol' },
  '142': { paoMonths: 36, warnings: W2, inci: 'Alcohol denat., Parfum, Hexamethylindanopyran, Tetramethyl acetyloctahydronaphthalenes, Juniperus virginiana oil, Hydroxycitronellal, Pogostemon cablin oil, Geraniol, Vanillin, Myroxylon pereirae oil, Linalool, Benzyl benzoate, Alpha-isomethyl ionone, Limonene, Rose ketones, Linalyl acetate, Citrus limon peel oil, Benzyl cinnamate, Citronellol, Trimethylbenzenepropanol, Cinnamyl alcohol, Methyl 2-octynoate, Camphor, Beta-caryophyllene, Geranyl acetate, Terpineol, Citral' },
  '147M': { paoMonths: 36, warnings: W1, inci: 'Alcohol denat., Parfum, Vanillin, Tetramethyl acetyloctahydronaphthalenes, Pogostemon cablin oil, Benzyl benzoate, Limonene, Acetylcedrene, Pinene, Coumarin, Linalool, Citronellol, Lavandula oil / extract, Beta-caryophyllene, Linalyl acetate, Juniperus virginiana oil, Terpineol, Rose ketones, Terpinolene, Citral, Alpha-terpinene, Geranyl acetate, Camphor, Eugenol, Geraniol, Farnesol, Carvone, Cananga odorata oil / extract' },
  '039W': { paoMonths: 36, warnings: 'Nie spryskiwać na otwarty ogień ani rozgrzane powierzchnie; Unikać kontaktu z oczami', inci: 'Alcohol denat., Parfum, Hexamethylindanopyran, Limonene, Linalyl acetate, Citrus aurantium peel oil, Benzyl salicylate, Hexyl cinnamal, Pogostemon cablin oil, Citronellol, Linalool, Benzyl alcohol, Alpha isomethyl ionone, Pinene, Geraniol, Eugenol, Cinnamyl alcohol, Rose ketones, Beta-caryophyllene, Terpineol, Citral, Alpha-terpinene' },
  '116W': { paoMonths: 36, warnings: W1, inci: 'Alcohol denat., Parfum, Tetramethyl acetyloctahydronaphthalenes, Benzyl salicylate, Hydroxycitronellal, Linalyl acetate, Vanillin, Limonene, Rose ketones, Coumarin, Pinene, Linalool, Benzyl alcohol, Benzyl benzoate, Benzyl cinnamate, Beta-caryophyllene, Citrus aurantium peel oil' },
  '002M': { paoMonths: 36, warnings: W1, inci: 'Alcohol denat., Parfum, Linalool, Linalyl acetate, Hexamethylindanopyran, Limonene, Tetramethyl acetyloctahydronaphthalenes, Citrus limon peel oil, Acetylcedrene, Citrus aurantium peel oil, Alpha-isomethyl ionone, Pinene, Geraniol, Citral, Geranyl acetate, Citronellol, Eugenol, Rose ketones, Camphor, Terpineol, Beta-caryophyllene, Terpinolene, Alpha-terpinene' },
  '148W': { paoMonths: 36, warnings: W2, inci: 'Alcohol denat., Parfum, Tetramethyl acetyloctahydronaphthalenes, Vanillin, Hexamethylindanopyran, Benzyl salicylate, Linalool, Linalyl acetate, Hydroxycitronellal, Benzyl benzoate, Limonene, Lavandula oil / extract, Coumarin, Citrus limon peel oil, Pinene, Terpineol, Benzyl cinnamate, Beta-caryophyllene, Rose ketones, Isoeugenyl acetate, Camphor, Citral, Geraniol, Geranyl acetate, Terpinolene, Benzyl alcohol, Citronellol, Alpha-terpinene, Isoeugenol' },
  '072U': { paoMonths: 36, warnings: W3, inci: 'Alcohol denat., Parfum, Pogostemon cablin oil, Benzyl benzoate, Hexamethylindanopyran, Coumarin, Beta-caryophyllene, Alpha-isomethyl ionone, Vanillin, Cananga odorata oil / extract, Juniperus virginiana oil, Pinene, Acetylcedrene, Limonene, Geranyl acetate, Farnesol, Terpineol, Eugenol, Linalool, Camphor, Terpinolene, Geraniol, Isoeugenol, Isoeugenyl acetate' },
  '022M': { paoMonths: 36, warnings: W2, inci: 'Alcohol denat., Tetramethyl acetyloctahydronaphthalenes, Parfum, Limonene, Linalyl acetate, Pogostemon cablin oil, Juniperus virginiana oil, Citrus limon peel oil, Hexyl cinnamal, Hydroxycitronellal, Citronellol, Linalool, Citrus aurantium peel oil, Citral, Beta-caryophyllene, Pelargonium graveolens flower oil, Geraniol, Terpineol, Terpinolene, Benzyl benzoate, Alpha-terpinene' },
  '133W': { paoMonths: 36, warnings: 'Nie spryskiwać na otwarty ogień ani rozgrzane powierzchnie; Unikać kontaktu z oczami; Trzymać poza zasięgiem dzieci', inci: 'Alcohol denat., Parfum, Tetramethyl acetyloctahydronaphthalenes, Vanillin, Linalool, Benzyl salicylate, Linalyl acetate, Limonene, Hydroxycitronellal, Citrus aurantium peel oil, Benzyl benzoate, Citrus limon peel oil, Coumarin, Dimethyl phenethyl acetate, Geranyl acetate, Citronellol, Pinene, Geraniol, Terpineol, Juniperus virginiana oil, Trimethylbenzenepropanol, Rose ketones, Citral, Beta-caryophyllene, Terpinolene, Benzaldehyde, Alpha-terpinene, Benzyl alcohol' },
  '161W': { paoMonths: 36, warnings: W1, inci: 'Alcohol denat., Parfum, Vanillin, Benzyl salicylate, Tetramethyl acetyloctahydronaphthalenes, Hydroxycitronellal, Linalyl acetate, Geranyl acetate, Coumarin, Alpha-isomethyl ionone, Linalool, Limonene, Citrus aurantium peel oil, Jasmine oil / extract, Isoeugenyl acetate, Myroxylon pereirae oil / extract, Benzyl benzoate, Benzyl alcohol, Pinene, Benzyl cinnamate, Rose ketones, Citronellol, Cananga odorata oil / extract, Geraniol, Eugenol, Isoeugenol, Terpineol, Beta-caryophyllene, Citral, Benzaldehyde, Farnesol' },
  '162M': { paoMonths: 36, warnings: W1, inci: 'Alcohol denat., Parfum, Tetramethyl acetyloctahydronaphthalenes, Acetylcedrene, Linalyl acetate, Limonene, Hydroxycitronellal, Alpha-isomethyl ionone, Pinene, Coumarin, Benzyl benzoate, Citronellol, Linalool, Lavandula oil / extract, Citrus aurantium peel oil, Beta-caryophyllene, Cedrus atlantica oil / extract, Trimethylcyclopentenyl methylisopentenol, Juniperus virginiana oil, Geranyl acetate, Citral, Vanillin, Menthol, Geraniol, Terpineol, Rose ketones, Pogostemon cablin oil, Camphor, Terpinolene, Alpha terpinene, Cinnamomum zeylanicum bark oil, Cinnamal, Isoeugenol, Anethole, Eugenol, Carvone, Farnesol' },
  '028W': { paoMonths: 36, warnings: 'Nie spryskiwać na otwarty ogień ani inne źródła zapłonu; Unikać kontaktu z oczami; Trzymać poza zasięgiem dzieci', inci: 'Alcohol denat., Parfum, Hexyl cinnamal, Pogostemon cablin oil, Hexamethylindanopyran, Linalool, Coumarin, Linalyl acetate, Limonene, Vanillin, Citrus limon peel oil, Benzyl benzoate, Beta-caryophyllene, Pinene, Citronellol, Geraniol, Terpineol, Benzaldehyde, Citral, Alpha-terpinene, Amyl cinnamal, Eugenol, Menthol, Acetylcedrene, Terpinolene, Geranyl acetate, Cinnamal, Benzyl alcohol, Anise alcohol, Methyl salicylate, Benzyl salicylate' },
  '032M': { paoMonths: 36, warnings: W1, inci: 'Alcohol denat., Parfum, Tetramethyl acetyloctahydronaphthalenes, Hexamethylindanopyran, Limonene, Linalyl acetate, Coumarin, Juniperus virginiana oil, Citrus aurantifolia peel oil, Linalool, Pinene, Terpineol, Vanillin, Beta-caryophyllene, Terpinolene, Eugenol, Lavandula oil/extract, Pelargonium graveolens flower oil, Citronellol, Citral, Camphor, Rose ketones, Alpha-terpinene, Citrus limon peel oil, Carvone, Sclareol, Geraniol, Geranyl acetate, Isoeugenol, Farnesol' },
  '105U': { paoMonths: 36, warnings: 'Nie spryskiwać na otwarty ogień ani na rozgrzane powierzchnie; Unikać kontaktu z oczami', inci: 'Alcohol denat., Parfum, Geranyl acetate, Rose ketones, Citrus aurantium peel oil, Limonene, Citronellol, Geraniol, Vanillin, Anise alcohol' },
  '062M': { paoMonths: 36, warnings: 'Nie spryskiwać na otwarty ogień ani na rozgrzane powierzchnie; Trzymać poza zasięgiem dzieci', inci: 'Alcohol denat., Parfum, Tetramethyl acetyloctahydronaphthalenes, Linalyl acetate, Linalool, Citrus limon peel oil, Limonene, Hexamethylindanopyran, Coumarin, Pinene, Citral, Geranyl acetate, Terpineol, Rose ketones, Eucalyptus globulus oil, Vanillin, Benzyl cinnamate, Benzyl benzoate, Geraniol, Benzaldehyde, Beta-caryophyllene, Anethole' },
  '023W': { paoMonths: 36, warnings: W3, inci: 'Alcohol denat., Parfum, Vanillin, Hexamethylindanopyran, Trimethylbenzenepropanol, Benzyl benzoate, Hexyl cinnamal, Anethole, Coumarin, Amyl salicylate' },
  '090W': { paoMonths: 36, warnings: W2, inci: 'Alcohol denat., Parfum, Linalool, Vanillin, Linalyl acetate, Limonene, Hydroxycitronellal, Coumarin, Citrus aurantium peel oil, Hexyl cinnamal, Juniperus virginiana oil, Anethole, Alpha-isomethyl ionone, Citronellol, Pinene, Benzaldehyde, Rose ketones, Santalol, Beta-caryophyllene, Citral, Geranyl acetate, Geraniol, Terpinolene, Benzyl alcohol, Terpineol' },
  '003M': { paoMonths: 36, warnings: W1, inci: 'Alcohol denat., Parfum, Tetramethyl acetyloctahydronaphthalenes, Citrus limon peel oil, Acetylcedrene, Limonene, Hexamethylindanopyran, Linalyl acetate, Benzyl benzoate, Pinene, Linalool, Pogostemon cablin oil, Coumarin, Amyl salicylate, Lavandula oil / extract, Juniperus virginiana oil, Citral, Eugenol, Vanillin, Beta-caryophyllene, Terpinolene, Camphor, Alpha-terpinene, Geraniol, Terpineol, Benzyl cinnamate, Cinnamyl alcohol' },
  '145A': { paoMonths: 36, warnings: W2, inci: 'Alcohol denat., Parfum, Tetramethyl acetyloctahydronaphthalenes, Vanillin, Hexamethylindanopyran, Limonene, Citrus aurantium peel oil, Citrus limon peel oil, Benzyl benzoate, Linalool, Citral, Pinene, Geraniol, Linalyl acetate, Terpineol, Geranyl acetate, Citronellol, Benzaldehyde, Beta-caryophyllene, Rose ketones, Terpinolene, Alpha-terpinene, Farnesol, Isoeugenol, Carvone, Benzyl alcohol, Eugenol, Benzyl cinnamate' },
  '044A': { paoMonths: 36, warnings: W2, inci: 'Alcohol denat., Parfum, Citrus limon peel oil, Limonene, Linalyl acetate, Linalool, Santalum album oil, Citral, Santalol, Rose ketones, Tetramethyl acetyloctahydronaphthalenes, Alpha-isomethyl ionone, Terpinolene, Beta-caryophyllene, Terpineol, Alpha-terpinene, Geraniol, Citronellol, Farnesol' },
  '068M': { paoMonths: 36, warnings: W1, inci: 'Alcohol denat., Parfum, Tetramethyl acetyloctahydronaphthalenes, Linalyl acetate, Citrus limon peel oil, Linalool, Limonene, Pogostemon cablin oil, Citral, Beta-caryophyllene, Rose ketones, Terpineol, Vanillin, Citronellol, Terpinolene, Camphor, Geranyl acetate, Geraniol, Alpha-terpinene' },
  '120W': { paoMonths: 36, warnings: W2, inci: 'Alcohol denat., Parfum, Tetramethyl acetyloctahydronaphthalenes, Citrus limon peel oil, Linalyl acetate, Limonene, Trimethylbenzenepropanol, Pogostemon cablin oil, Coumarin, Citronellol, Anethole, Hexamethylindanopyran, Vanillin, Linalool, Pinene, Geraniol, Citral, Benzaldehyde, Rose ketones, Eugenol, Benzyl alcohol, Geranyl acetate, Beta-caryophyllene, Terpinolene, Terpineol, Alpha-terpinene' },
  '025A': { paoMonths: 36, warnings: W2, inci: 'Alcohol denat., Parfum, Benzyl salicylate, Benzyl benzoate, Pogostemon cablin oil, Linalyl acetate, Linalool, Hydroxycitronellal, Hexyl cinnamal, Geraniol, Pinene, Hexamethylindanopyran, Beta caryophyllene, Citronellol, Vanillin, Cananga odorata oil, Alpha-terpinene, Benzyl alcohol, Benzaldehyde, Limonene, Eugenol, Geranyl acetate, Citral, Farnesol, Cinnamal' },
  '115W': { paoMonths: 36, warnings: W3, inci: 'Alcohol denat., Parfum, Hydroxycitronellal, Benzyl benzoate, Citronellol, Dimethylbenzyl carbinyl acetate, Geranyl acetate, Alpha-isomethyl ionone, Geraniol, Linalyl acetate, Linalool, Trimethylbenzenepropanol, Hexyl cinnamal, Citrus limon peel oil, Pogostemon cablin oil, Limonene, Terpineol, Juniperus virginiana oil, Rose ketones, Coumarin, Vanillin, Beta-caryophyllene, Citrus aurantium peel oil, Rosa flower oil / extract, Citral, Methyl 2-octynoate, Benzyl alcohol, Eugenol' },
  '084M': { paoMonths: 36, warnings: W1, inci: 'Alcohol denat., Parfum, Tetramethyl acetyloctahydronaphthalenes, Hexamethylindanopyran, Linalyl acetate, Linalool, Citrus limon peel oil, Limonene, Coumarin, Citronellol, Pogostemon cablin oil, Pinene, Alpha-isomethyl ionone, Rose ketones, Mentha piperita oil, Citral, Pelargonium graveolens flower oil, Anethole, Menthol, Beta-caryophyllene, Geraniol, Farnesol, Terpineol, Terpinolene, Camphor' },
  '027W': { paoMonths: 36, warnings: W1, inci: 'Alcohol denat., Parfum, Hexamethylindanopyran, Tetramethyl acetyloctahydronaphthalenes, Alpha-isomethyl ionone, Hydroxycitronellal, Citronellol, Benzyl benzoate, Vanillin, Cinnamyl alcohol, Dimethylbenzyl carbinyl acetate, Benzyl salicylate, Geraniol, Linalyl acetate, Linalool, Coumarin, Citrus limon peel oil, Limonene, Eugenol, Geranyl acetate, Rose ketones, Terpineol, Beta-caryophyllene, Citral' },
  '154W': { paoMonths: 36, warnings: W2, inci: 'Alcohol denat., Parfum, Hexamethylindanopyran, Alpha-isomethyl ionone, Linalyl acetate, Linalool, Citrus limon peel oil, Cinnamyl alcohol, Limonene, Isoeugenyl acetate, Coumarin, Pinene, Benzyl salicylate, Rose ketones, Vanillin, Citral, Farnesol, Terpineol, Eugenol, Beta-caryophyllene, Geranyl acetate, Terpinolene, Geraniol' },
  '056W': { paoMonths: 36, warnings: W2, inci: 'Alcohol denat., Parfum, Tetramethyl acetyloctahydronaphthalenes, Hexamethylindanopyran, Vanillin, Limonene, Alpha-isomethyl ionone, Pogostemon cablin oil, Citrus aurantium peel oil, Isoeugenyl acetate, Geraniol, Hydroxycitronellal, Coumarin, Pinene, Beta-caryophyllene, Benzaldehyde, Citronellol, Citral, Terpineol, Linalool, Alpha-terpinene' },
  '040W': { paoMonths: 36, warnings: W2, inci: 'Alcohol denat., Parfum, Hexamethylindanopyran, Linalyl acetate, Limonene, Linalool, Citrus limon peel oil, Hydroxycitronellal, Vanillin, Pogostemon cablin oil, Geraniol, Pinene, Citral, Citronellol, Beta-caryophyllene, Geranyl acetate, Terpineol, Alpha-terpinene, Terpinolene' },
  '030A': { paoMonths: 36, warnings: W2, inci: 'Alcohol denat., Tetramethyl acetyloctahydronaphthalenes, Parfum, Limonene, Linalool, Hexamethylindanopyran, Citrus limon peel oil, Citrus aurantium peel oil, Juniperus virginiana oil, Pogostemon cablin oil, Pinene, Citral, Beta-caryophyllene, Linalyl acetate, Terpineol, Rose ketones, Terpinolene, Dimethylbenzyl carbinyl acetate, Alpha-terpinene, Carvone, Menthol, Mentha viridis leaf oil, Geraniol, Camphor, Citronellol, Eucalyptus globulus oil, Cinnamal' },
  '051W': { paoMonths: 36, warnings: W1, inci: 'Alcohol denat., Parfum, Linalool, Hexamethylindanopyran, Tetramethyl acetyloctahydronaphthalenes, Pogostemon cablin oil, Limonene, Linalyl acetate, Citrus aurantium bergamia peel oil, Benzyl salicylate, Trimethylbenzenepropanol, Citrus aurantium peel oil, Hydroxycitronellal, Geranyl acetate, Citronellol, Hexyl cinnamal, Coumarin, Geraniol, Vanillin, Beta-caryophyllene, Pinene, Rose ketones, Citral, Terpineol, Alpha-terpinene, Eugenol, Terpinolene, Benzyl alcohol, Benzyl benzoate, Benzyl cinnamate, Benzaldehyde, Farnesol' },
  '136M': { paoMonths: 36, warnings: W1, inci: 'Alcohol denat., Parfum, Tetramethyl acetyloctahydronaphthalenes, Linalool, Linalyl acetate, Juniperus virginiana oil, Limonene, Citrus aurantium peel oil, Hexamethylindanopyran, Coumarin, Alpha-isomethyl ionone, Pinene, Acetylcedrene, Terpinolene, Vanillin, Pogostemon cablin oil, Beta-caryophyllene, Myroxylon pereirae oil / extract, Benzyl benzoate, Citral, Terpineol, Camphor, Geranyl acetate, Benzyl cinnamate, Citronellol, Geraniol, Rose ketones, Alpha-terpinene, Sclareol, Carvone, Benzyl alcohol, Eugenol, Farnesol, Cinnamyl alcohol, Benzaldehyde' },
  '132W': { paoMonths: 36, warnings: W1, inci: 'Alcohol denat., Parfum, Tetramethyl acetyloctahydronaphthalenes, Linalool, Benzyl salicylate, Linalyl acetate, Hydroxycitronellal, Citrus aurantium bergamia peel oil, Limonene, Hexyl cinnamal, Geranyl acetate, Geraniol, Citronellol, Pinene, Trimethylcyclopentenyl methylisopentenol, Eugenol, Jasmine oil / extract, Rose ketones, Citral, Alpha-isomethyl ionone, Cananga odorata oil / extract, Beta-caryophyllene, Benzyl benzoate, Terpinolene, Terpineol, Rose flower oil / extract, Benzyl alcohol, Alpha terpinene, Farnesol, Camphor, Isoeugenol' },
  '110U': { paoMonths: 36, warnings: W1, inci: 'Alcohol denat., Parfum, Hexamethylindanopyran, Benzyl salicylate, Tetramethyl acetyloctahydronaphthalenes, Geranyl acetate, Linalyl acetate, Limonene, Rose ketones, Vanillin, Hydroxycitronellal, Coumarin' },
  '054U': { paoMonths: 36, warnings: W1, inci: 'Alcohol denat., Parfum, Tetramethyl acetyloctahydronaphthalenes, Hexamethylindanopyran, Pogostemon cablin oil, Acetylcedrene, Linalool, Vanillin, Cinnamyl alcohol, Citronellol, Citrus limon peel oil, Linalyl acetate, Limonene, Geraniol, Eugenol, Coumarin, Beta-caryophyllene, Pinene, Isoeugenyl acetate, Amyl salicylate, Geranyl acetate, Hydroxycitronellal, Citral, Cinnamomum zeylanicum bark oil, Alpha-terpinene, Camphor, Terpinolene, Isoeugenol, Anise alcohol' },
  '347W': { paoMonths: 36, warnings: W1, inci: 'Alcohol denat., Parfum, Tetramethyl acetyloctahydronaphthalenes, Alpha-isomethyl ionone, Benzyl salicylate, Hydroxycitronellal, Geraniol, Coumarin, Terpineol, Linalool, Eugenol, Rose ketones, Linalyl acetate' },
  '033M': { paoMonths: 36, warnings: W1, inci: 'Alcohol denat., Parfum, Tetramethyl acetyloctahydronaphthalenes, Citrus aurantium bergamia peel oil, Hexamethylindanopyran, Limonene, Linalyl acetate, Linalool, Coumarin, Citrus limon peel oil, Hydroxycitronellal, Pinene, Hexyl cinnamal, Alpha-isomethyl ionone, Lavandula officinalis flower oil, Vanillin, Geraniol, Citronellol, Juniperus virginiana oil, Amyl salicylate, Citral, Geranyl acetate, Camphor, Anethole, Rose ketones, Beta-caryophyllene, Terpinolene, Terpineol, Alpha-terpinene' },
  '020M': { paoMonths: 36, warnings: W1, inci: 'Alcohol denat., Parfum, Tetramethyl acetyloctahydronaphthalenes, Acetylcedrene, Hexamethylindanopyran, Linalool, Linalyl acetate, Coumarin, Geraniol, Limonene, Alpha-isomethyl ionone, Vanillin, Juniperus virginiana oil, Citrus aurantium peel oil, Pinene, Rose ketones, Citrus limon peel oil, Citronellol, Geranyl acetate, Terpineol, Citral, Terpinolene, Beta-caryophyllene, Evernia prunastri extract, Benzyl alcohol, Alpha-terpinene' },
  '099U': { paoMonths: 36, warnings: W2, inci: 'Alcohol denat., Parfum, Limonene, Linalyl acetate, Citrus aurantium peel oil, Linalool, Hexamethylindanopyran, Citrus limon peel oil, Benzyl salicylate, Menthol, Tetramethyl acetyloctahydronaphthalenes, Hydroxycitronellal, Citral, Lavandula angustifolia flower/leaf/stem extract, Carvone, Beta-caryophyllene, Pogostemon cablin oil, Terpineol, Farnesol, Eugenol, Geranyl acetate, Geraniol, Mentha piperita oil, Camphor, Rose ketones, Benzyl alcohol, Alpha-terpinene, Terpinolene, Alpha-isomethyl ionone, Citronellol, Isoeugenol' },
  '049W': { paoMonths: 36, warnings: W2, inci: 'Alcohol denat., Parfum, Tetramethyl acetyloctahydronaphthalenes, Alpha-isomethyl ionone, Benzyl salicylate, Hexamethylindanopyran, Linalool, Hydroxycitronellal, Citronellol, Hexyl cinnamal, Linalyl acetate, Dimethyl phenethyl acetate, Pogostemon cablin oil, Trimethylcyclopentenyl methylisopentenol, Geraniol, Geranyl acetate, Pinene, Vanillin, Isoeugenyl acetate, Rose ketones, Beta-caryophyllene, Coumarin, Benzyl alcohol, Citral, Benzaldehyde, Alpha-terpinene' },
  '031M': { paoMonths: 36, warnings: W2, inci: 'Alcohol denat., Parfum, Hexamethylindanopyran, Tetramethyl acetyloctahydronaphthalenes, Acetylcedrene, Linalool, Linalyl acetate, Juniperus virginiana oil, Citrus limon peel oil, Citronellol, Geraniol, Citral, Trimethylcyclopentenyl methylisopentenol, Coumarin, Pogostemon cablin oil, Terpineol, Beta-caryophyllene, Terpinolene, Camphor, Geranyl acetate, Alpha-terpinene' },
  '091M': { paoMonths: 36, warnings: W1, inci: 'Alcohol denat., Parfum, Hexamethylindanopyran, Tetramethyl acetyloctahydronaphthalenes, Linalyl acetate, Linalool, Limonene, Pinene, Coumarin, Evernia prunastri extract, Citral, Terpinolene, Citrus limon peel oil, Terpineol, Sclareol, Geraniol, Geranyl acetate, Isoeugenol, Alpha-terpinene, Carvone' },
  '021M': { paoMonths: 36, warnings: W1, inci: 'Alcohol denat., Parfum, Linalool, Tetramethyl acetyloctahydronaphthalenes, Linalyl acetate, Hexamethylindanopyran, Citrus limon peel oil, Limonene, Pinene, Juniperus virginiana oil, Pogostemon cablin oil, Hexyl cinnamal, Trimethylbenzenepropanol, Alpha-isomethyl ionone, Citral, Beta-caryophyllene, Sclareol, Citronellol, Terpineol, Geraniol, Terpinolene, Camphor, Alpha-terpinene, Geranyl acetate, Farnesol, Isoeugenol' },
  '037M': { paoMonths: 36, warnings: W2, inci: 'Alcohol denat., Parfum, Tetramethyl acetyloctahydronaphthalenes, Pogostemon cablin oil, Limonene, Linalool, Citrus limon peel oil, Linalyl acetate, Pinene, Citronellol, Beta-caryophyllene, Juniperus virginiana oil, Citral, Terpineol, Alpha-terpinene, Terpinolene, Geranyl acetate, Geraniol, Eugenol, Cinnamyl alcohol, Benzyl cinnamate, Cinnamal' },
  '088M': { paoMonths: 36, warnings: W2, inci: 'Alcohol denat., Parfum, Tetramethyl acetyloctahydronaphthalenes, Linalyl acetate, Citrus limon peel oil, Limonene, Linalool, Coumarin, Hexamethylindanopyran, Pinene, Pogostemon cablin oil, Vanillin, Beta caryophyllene, Citronellol, Eugenol, Citral, Cinnamyl alcohol, Terpineol, Terpinolene, Alpha-terpinene, Geraniol, Evernia prunastri extract, Benzyl alcohol, Farnesol, Isoeugenol, Juniperus virginiana oil' },
  '078M': { paoMonths: 36, warnings: W2, inci: 'Alcohol denat., Parfum, Linalool, Hexamethylindanopyran, Linalyl acetate, Tetramethyl acetyloctahydronaphthalenes, Limonene, Vanillin, Citrus aurantium peel oil, Hydroxycitronellal, Pinene, Pogostemon cablin oil, Geranyl acetate, Citrus limon peel oil, Mentha piperita oil, Menthol, Camphor, Beta-caryophyllene, Citral, Terpinolene, Geraniol, Terpineol, Alpha-terpinene, Citronellol, Carvone, Benzyl alcohol' },
  '066M': { paoMonths: 36, warnings: W2, inci: 'Alcohol denat., Parfum, Pogostemon cablin oil, Hexamethylindanopyran, Citrus limon peel oil, Linalyl acetate, Limonene, Pelargonium graveolens flower oil, Beta-caryophyllene, Citronellol, Rose ketones, Citral, Geraniol, Benzyl benzoate, Benzaldehyde, Benzyl cinnamate, Cinnamal, Terpinolene' },
  '060M': { paoMonths: 36, warnings: W2, inci: 'Alcohol denat., Parfum, Tetramethyl acetyloctahydronaphthalenes, Hexamethylindanopyran, Acetylcedrene, Linalyl acetate, Citrus limon peel oil, Limonene, Rose ketones, Linalool, Alpha-isomethyl ionone, Citral, Lavandula angustifolia oil, Coumarin, Citronellol, Alpha-terpinene' },
  '015M': { paoMonths: 36, warnings: W2, inci: 'Alcohol denat., Parfum, Tetramethyl acetyloctahydronaphthalenes, Limonene, Linalool, Hexamethylindanopyran, Linalyl acetate, Pelargonium graveolens flower oil, Geraniol, Citrus limon peel oil, Citrus aurantium bergamia oil, Citronellol, Vanillin, Coumarin, Citral, Hydroxycitronellal, Terpineol, Geranyl acetate, Beta-caryophyllene, Terpinolene, Sclareol, Alpha-terpinene' },
  // Pages 51-70 products
  '108M': { paoMonths: 36, warnings: W2, inci: 'Alcohol denat., Parfum, Acetylcedrene, Tetramethyl acetyloctahydronaphthalenes, Linalyl acetate, Limonene, Alpha-isomethyl ionone, Linalool, Hexamethylindanopyran, Pinene, Lavandula oil/extract, Citrus limon peel oil, Citrus aurantium bergamia peel oil, Alpha-terpinene, Camphor, Hydroxycitronellal, Citral, Citronellol, Rose ketones, Terpineol, Geraniol, Beta-caryophyllene, Geranyl acetate' },
  '071W': { paoMonths: 36, warnings: W2, inci: 'Alcohol denat., Parfum, Linalyl acetate, Linalool, Benzyl salicylate, Limonene, Hexamethylindanopyran, Citrus limon peel oil, Citrus aurantium bergamia peel oil, Hexyl cinnamal, Benzyl benzoate, Pinene, Tetramethyl acetyloctahydronaphthalenes, Citronellol, Cananga odorata flower oil, Santalum album oil, Acetylcedrene, Alpha-isomethyl ionone, Geraniol, Vanillin, Coumarin, Pelargonium graveolens flower oil, Citral, Dimethylbenzyl carbinyl acetate, Geranyl acetate, Eugenol, Benzyl alcohol, Terpinolene, Beta-caryophyllene, Farnesol, Alpha-terpinene, Terpineol, Menthol' },
  '098W': { paoMonths: 36, warnings: W2, inci: 'Alcohol denat., Parfum, Linalyl acetate, Benzyl salicylate, Linalool, Limonene, Hexyl cinnamal, Citrus limon peel oil, Hydroxycitronellal, Citronellol, Citrus aurantium peel oil, Vanillin, Acetylcedrene, Alpha isomethyl ionone, Dimethylbenzyl carbinyl acetate, Pogostemon cablin oil, Cananga odorata flower oil, Coumarin, Citral, Beta-caryophyllene, Trimethylcyclopentenyl methylisopentenol, Geranyl acetate, Benzyl benzoate, Geraniol, Terpineol, Terpinolene, Rose ketones, Farnesol, Alpha-terpinene' },
  '097W': { paoMonths: 36, warnings: W2, inci: 'Alcohol denat., Parfum, Limonene, Vanillin, Citrus aurantium peel oil, Citrus limon peel oil, Linalyl acetate, Geranyl acetate, Citronellol, Geraniol, Rose ketones, Coumarin, Linalool, Citral, Benzyl benzoate, Benzyl cinnamate' },
  '082W': { paoMonths: 36, warnings: W2, inci: 'Alcohol denat., Parfum, Hexamethylindanopyran, Tetramethyl acetyloctahydronaphthalenes, Benzyl salicylate, Limonene, Linalyl acetate, Citrus limon peel oil, Hexyl cinnamal, Pogostemon cablin oil, Hydroxycitronellal, Citronellol, Geraniol, Geranyl acetate, Linalool, Alpha-isomethyl ionone, Rose ketones, Vanillin, Benzaldehyde, Beta-caryophyllene, Citral, Isoeugenyl acetate, Terpinolene, Alpha terpinene' },
  '076W': { paoMonths: 36, warnings: W3, inci: 'Alcohol denat., Parfum, Tetramethyl acetyloctahydronaphthalenes, Hexamethylindanopyran, Limonene, Benzyl benzoate, Citrus aurantium peel oil, Hydroxycitronellal, Citrus limon peel oil, Citronellol, Juniperus virginiana oil, Alpha-isomethyl ionone, Hexyl cinnamal, Geranyl acetate, Pinene, Linalool, Mentha viridis leaf oil, Geraniol, Terpineol, Carvone, Citral, Rose ketones, Anethole, Beta-caryophyllene, Menthol, Cinnamal, Terpinolene, Benzyl alcohol, Amyl salicylate, Alpha-terpinene' },
  '064A': { paoMonths: 36, warnings: W2, inci: 'Alcohol denat., Parfum, Limonene, Dimethylbenzyl carbinyl acetate, Citronellol, Benzyl salicylate, Citrus aurantium peel oil, Linalool, Linalyl acetate, Alpha-isomethyl ionone, Citrus limon peel oil, Beta-caryophyllene, Hydroxycitronellal, Geraniol, Pogostemon cablin oil, Farnesol, Citral, Rose flower oil/extract, Terpineol, Cananga odorata flower oil, Benzyl alcohol, Benzyl benzoate, Geranyl acetate, Terpinolene, Methyl salicylate, Amyl cinnamal' },
  '057W': { paoMonths: 36, warnings: 'Nie spryskiwać na inne źródła zapłonu; Unikać kontaktu z oczami', inci: 'Alcohol denat., Parfum, Hexamethylindanopyran, Tetramethyl acetyloctahydronaphthalenes, Linalyl acetate, Hexyl cinnamal, Linalool, Citrus aurantium peel oil, Limonene, Citronellol, Alpha-isomethyl ionone, Hydroxycitronellal, Benzaldehyde, Pinene, Geraniol, Citral, Terpineol, Terpinolene' },
  '093W': { paoMonths: 36, warnings: W2, inci: 'Alcohol denat., Parfum, Citrus limon peel oil, Linalyl acetate, Tetramethyl acetyloctahydronaphthalenes, Limonene, Juniperus virginiana oil, Linalool, Pogostemon cablin oil, Citronellol, Citral, Hexyl cinnamal, Geraniol, Hydroxycitronellal, Beta-caryophyllene, Rose flower oil/extract, Terpineol, Terpinolene, Benzyl benzoate, Rose ketones, Alpha-terpinene, Isoeugenyl acetate, Eugenol' },
  '089W': { paoMonths: 36, warnings: W1, inci: 'Alcohol denat., Parfum, Benzyl salicylate, Linalool, Tetramethyl acetyloctahydronaphthalenes, Hydroxycitronellal, Pogostemon cablin oil, Linalyl acetate, Limonene, Hexyl cinnamal, Dimethyl phenethyl acetate, Pinene, Citrus aurantium peel oil, Citronellol, Geraniol, Geranyl acetate, Vanillin, Beta-caryophyllene, Rose ketones, Benzyl benzoate, Alpha-terpinene, Citral, Benzyl alcohol, Terpinolene, Citrus limon peel oil, Terpineol, Sclareol, Eugenol' },
  '135U': { paoMonths: 36, warnings: W2, inci: 'Alcohol denat., Parfum, Hexamethylindanopyran, Hexadecanolactone, Limonene, Terpineol, Beta-caryophyllene' },
  '100U': { paoMonths: 36, warnings: W2, inci: 'Alcohol denat., Parfum, Hexamethylindanopyran, Vanillin, Hydroxycitronellal, Linalool, Cinnamyl alcohol, Linalyl acetate, Amyl salicylate, Methyl 2-octynoate, Benzyl alcohol' },
  '073U': { paoMonths: 36, warnings: W2, inci: 'Alcohol denat., Parfum, Tetramethyl acetyloctahydronaphthalenes, Citrus limon peel oil, Limonene, Hexamethylindanopyran, Acetylcedrene, Linalyl acetate, Benzyl salicylate, Linalool, Pogostemon cablin oil, Coumarin, Alpha-isomethyl ionone, Lavandula angustifolia oil, Sclareol, Citral, Citronellol, Geraniol, Rose ketones, Terpineol, Amyl salicylate, Beta-caryophyllene, Carvone, Alpha-terpinene, Camphor, Terpinolene, Vanillin, Isoeugenol, Hydroxycitronellal, Geranyl acetate, Eugenol' },
  '114U': { paoMonths: 36, warnings: W1, inci: 'Alcohol denat., Parfum, Pogostemon cablin oil, Vanillin, Linalool, Citronellol, Benzyl benzoate, Pelargonium graveolens flower oil, Limonene, Citrus limon peel oil, Geraniol, Beta-caryophyllene, Rose ketones, Rose flower oil/extract, Pinene, Linalyl acetate, Benzyl alcohol, Cinnamyl alcohol, Benzyl cinnamate, Eugenol, Cinnamomum zeylanicum bark oil, Citrus aurantium peel oil, Citral, Cinnamal, Farnesol, Dimethylbenzyl carbinyl acetate' },
  '019W': { paoMonths: 36, warnings: W1, inci: 'Alcohol denat., Parfum, Tetramethyl acetyloctahydronaphthalenes, Limonene, Citrus limon peel oil, Citrus aurantium peel oil, Benzyl salicylate, Alpha-isomethyl ionone, Hydroxycitronellal, Hexyl cinnamal, Vanillin, Pogostemon cablin oil, Pinene, Coumarin, Linalool, Linalyl acetate, Citronellol, Rose ketones, Citral, Beta-caryophyllene, Benzyl alcohol, Cananga odorata oil/extract, Benzyl benzoate, Menthol, Farnesol, Terpinolene, Terpineol, Alpha-terpinene, Geranyl acetate, Geraniol' },
  '001M': { paoMonths: 36, warnings: W1, inci: 'Alcohol denat., Parfum, Tetramethyl acetyloctahydronaphthalenes, Hexamethylindanopyran, Limonene, Coumarin, Hydroxycitronellal, Vanillin, Citrus aurantium peel oil, Citrus aurantium bergamia peel oil, Alpha-isomethyl ionone, Linalyl acetate, Pinene, Linalool, Rose ketones, Terpinolene, Eugenia caryophyllus oil, Cinnamomum zeylanicum bark oil, Eugenol, Menthol, Cinnamal, Citral, Terpineol, Alpha-terpinene, Geranyl acetate, Beta-caryophyllene, Citronellol, Isoeugenol, Geraniol' },
  '070W': { paoMonths: 36, warnings: W2, inci: 'Alcohol denat., Parfum, Hexamethylindanopyran, Limonene, Citrus limon peel oil, Benzyl salicylate, Tetramethyl acetyloctahydronaphthalenes, Hexadecanolactone, Geraniol, Linalyl acetate, Vanillin, Hexyl cinnamal, Linalool, Pinene, Citronellol, Citral, Hydroxycitronellal, Geranyl acetate, Benzyl alcohol, Beta-caryophyllene' },
  '004M': { paoMonths: 36, warnings: W2, inci: 'Alcohol denat., Parfum, Tetramethyl acetyloctahydronaphthalenes, Linalool, Acetylcedrene, Linalyl acetate, Limonene, Citrus aurantium peel oil, Citrus limon peel oil, Pinene, Alpha-isomethyl ionone, Hydroxycitronellal, Juniperus virginiana oil, Sclareol, Rose ketones, Citral, Beta-caryophyllene, Camphor, Anethole, Vanillin, Terpineol, Terpinolene, Alpha-terpinene, Geraniol, Geranyl acetate, Citronellol, Citrus aurantifolia peel oil' },
  '007W': { paoMonths: 36, warnings: W1, inci: 'Alcohol denat., Parfum, Hexyl cinnamal, Benzyl salicylate, Hydroxycitronellal, Linalyl acetate, Tetramethyl acetyloctahydronaphthalenes, Citronellol, Alpha-isomethyl ionone, Citrus limon peel oil, Terpineol, Limonene, Trimethylcyclopentenyl methylisopentenol, Linalool, Pelargonium graveolens flower oil, Pinene, Geraniol, Methyl 2-octynoate, Citral, Geranyl acetate, Vanillin, Rose ketones, Benzyl alcohol, Beta-caryophyllene, Benzyl benzoate, Benzaldehyde' },
  '018M': { paoMonths: 36, warnings: W1, inci: 'Alcohol denat., Parfum, Tetramethyl acetyloctahydronaphthalenes, Linalool, Linalyl acetate, Limonene, Hexyl cinnamal, Citrus aurantium peel oil, Citrus limon peel oil, Juniperus virginiana oil, Citronellol, Acetylcedrene, Pinene, Beta-caryophyllene, Geraniol, Coumarin, Terpineol, Citral, Camphor, Terpinolene, Geranyl acetate, Alpha-terpinene, Isoeugenol, Eugenol, Farnesol' },
  '012M': { paoMonths: 36, warnings: W1, inci: 'Alcohol denat., Parfum, Linalyl acetate, Limonene, Linalool, Lavandula oil/extract, Citral, Citrus aurantifolia peel oil, Alpha-isomethyl ionone, Citrus limon peel oil, Eugenia caryophyllus leaf oil, Eugenol, Pogostemon cablin oil, Pinene, Hexyl cinnamal, Coumarin, Beta-caryophyllene, Acetylcedrene, Geranyl acetate, Pelargonium graveolens flower oil, Cinnamyl alcohol, Carvone, Mentha viridis oil, Hydroxycitronellal, Eugenyl acetate, Geraniol, Citronellol, Terpineol, Evernia prunastri extract, Terpinolene, Camphor, Juniperus virginiana oil, Alpha-terpinene' },
  '094M': { paoMonths: 36, warnings: W3, inci: 'Alcohol denat., Parfum, Citrus aurantium bergamia peel oil, Tetramethyl acetyloctahydronaphthalenes, Limonene, Linalyl acetate, Linalool, Pogostemon cablin oil, Pinene, Citronellol, Lavandula angustifolia oil, Coumarin, Amyl salicylate, Pelargonium graveolens flower oil, Citral, Geranyl acetate, Terpinolene, Geraniol, Terpineol, Alpha-terpinene, Rose ketones, Vanillin, Mentha piperita oil' },
  '153W': { paoMonths: 36, warnings: W1, inci: 'Alcohol denat., Parfum, Tetramethyl acetyloctahydronaphthalenes, Hexamethylindanopyran, Dimethyl phenethyl acetate, Hydroxycitronellal, Hexyl cinnamal, Citrus limon peel oil, Linalyl acetate, Limonene, Rose ketones, Citronellol, Linalool, Pinene, Geraniol, Geranyl acetate, Beta-caryophyllene, Anethole, Citral, Vanillin, Eugenol, Benzaldehyde' },
  '029W': { paoMonths: 36, warnings: W2, inci: 'Alcohol denat., Parfum, Linalool, Benzyl benzoate, Coumarin, Alpha-isomethyl ionone, Hydroxycitronellal, Geraniol, Linalyl acetate, Hexamethylindanopyran, Vanillin, Limonene, Citronellol, Citrus aurantium peel oil, Geranyl acetate, Pinene, Benzyl salicylate, Eugenol, Isoeugenol, Citrus limon peel oil, Jasmine oil/extract, Benzyl alcohol, Isoeugenyl acetate, Citral, Methyl salicylate, Terpineol, Benzaldehyde, Eugenyl acetate, Cinnamal, Terpinolene' },
  '016M': { paoMonths: 36, warnings: W1, inci: 'Alcohol denat., Parfum, Tetramethyl acetyloctahydronaphthalenes, Linalyl acetate, Linalool, Vanillin, Alpha-isomethyl ionone, Coumarin, Hydroxycitronellal, Limonene, Citrus aurantium peel oil, Lavandula oil/extract, Camphor, Cinnamomum zeylanicum bark oil, Geranyl acetate, Terpineol, Cinnamal, Mentha viridis leaf oil, Citral, Carvone, Pinene, Eugenol, Geraniol, Beta-caryophyllene, Citronellol, Terpinolene, Benzyl alcohol, Alpha-terpinene' },
  '069M': { paoMonths: 36, warnings: W1, inci: 'Alcohol denat., Parfum, Benzyl salicylate, Terpineol, Pogostemon cablin oil, Hexyl cinnamal, Coumarin, Geraniol, Vanillin, Juniperus virginiana oil, Citrus limon peel oil, Citronellol, Limonene, Pinene, Beta-caryophyllene, Eucalyptus globulus oil, Linalool, Lavandula oil/extract, Benzyl alcohol, Linalyl acetate, Geranyl acetate, Camphor, Citral, Terpinolene, Menthol, Anise alcohol, Alpha-terpinene, Eugenol' },
  '121W': { paoMonths: 36, warnings: W1, inci: 'Alcohol denat., Parfum, Linalyl acetate, Linalool, Citrus limon peel oil, Pogostemon cablin oil, Limonene, Citronellol, Geraniol, Benzyl salicylate, Geranyl acetate, Pinene, Isoeugenyl acetate, Eugenol, Hexadecanolactone, Citral, Alpha-isomethyl ionone, Benzaldehyde, Coumarin, Rose ketones, Beta-caryophyllene, Trans-anethole, Terpineol, Terpinolene' },
  '085W': { paoMonths: 36, warnings: W2, inci: 'Alcohol denat., Parfum, Linalool, Tetramethyl acetyloctahydronaphthalenes, Hexamethylindanopyran, Linalyl acetate, Limonene, Citrus limon peel oil, Hydroxycitronellal, Pogostemon cablin oil, Hexyl cinnamal, Benzyl benzoate, Citronellol, Geranyl acetate, Beta-caryophyllene, Vanillin, Coumarin, Geraniol, Citral, Rose ketones, Benzyl benzoate, Terpinolene, Terpineol' },
  '079M': { paoMonths: 36, warnings: W1, inci: 'Alcohol denat., Parfum, Tetramethyl acetyloctahydronaphthalenes, Linalool, Linalyl acetate, Coumarin, Limonene, Citronellol, Acetylcedrene, Pinene, Lavandula oil/extract, Benzyl benzoate, Alpha-isomethyl ionone, Vanillin, Pogostemon cablin oil, Citral, Beta-caryophyllene, Rose ketones, Camphor, Geraniol, Terpineol, Mentha piperita oil, Citrus limon peel oil, Geranyl acetate, Anethole, Sclareol, Terpinolene, Hydroxycitronellal, Menthol, Cinnamal, Alpha-terpinene, Carvone, Amyl salicylate' },
  '014W': { paoMonths: 36, warnings: W3, inci: 'Alcohol denat., Parfum, Tetramethyl acetyloctahydronaphthalenes, Hexamethylindanopyran, Vanillin, Linalyl acetate, Citrus limon peel oil, Limonene, Alpha-isomethyl ionone, Juniperus virginiana oil, Geraniol, Linalool, Hydroxycitronellal, Trimethylcyclopentenyl methylisopentenol, Coumarin, Pinene, Citral, Benzyl alcohol, Benzaldehyde, Terpinolene, Citronellol, Beta-caryophyllene, Terpineol, Alpha-terpinene' },
  '010W': { paoMonths: 36, warnings: W1, inci: 'Alcohol denat., Parfum, Benzyl salicylate, Tetramethyl acetyloctahydronaphthalenes, Coumarin, Vanillin, Geranyl acetate, Geraniol, Alpha-isomethyl ionone, Citronellol, Pogostemon cablin oil, Benzyl alcohol, Rose ketones, Anethole, Citral, Amyl salicylate, Benzyl benzoate, Beta-caryophyllene, Benzaldehyde, Linalool, Pinene' },
  '048M': { paoMonths: 36, warnings: W1, inci: 'Alcohol denat., Parfum, Tetramethyl acetyloctahydronaphthalenes, Hexamethylindanopyran, Linalool, Limonene, Citrus limon peel oil, Linalyl acetate, Pinene, Pogostemon cablin oil, Lavandula oil/extract, Geranyl acetate, Citronellol, Citrus aurantium peel oil, Beta-caryophyllene, Citral, Coumarin, Pelargonium graveolens flower oil, Vanillin, Geraniol, Terpineol, Anethole, Alpha-terpinene, Camphor, Rose ketones, Terpinolene, Benzyl benzoate, Eugenol, Carvone' },
  '024W': { paoMonths: 36, warnings: W1, inci: 'Alcohol denat., Parfum, Tetramethyl acetyloctahydronaphthalenes, Hexamethylindanopyran, Linalool, Linalyl acetate, Limonene, Citrus limon peel oil, Vanillin, Hydroxycitronellal, Pogostemon cablin oil, Geraniol, Pinene, Citral, Citronellol, Beta-caryophyllene, Geranyl acetate, Terpineol, Alpha-terpinene, Terpinolene' },
  '086M': { paoMonths: 36, warnings: W1, inci: 'Alcohol denat., Parfum, Tetramethyl acetyloctahydronaphthalenes, Acetylcedrene, Linalyl acetate, Citronellol, Linalool, Citrus limon peel oil, Limonene, Coumarin, Eucalyptus globulus oil, Trimethylcyclopentenyl methylisopentenol, Sclareol, Pinene, Lavandula oil/extract, Rose ketones, Citral, Geraniol, Camphor, Geranyl acetate, Terpineol, Beta-caryophyllene' },
  '151W': { paoMonths: 36, warnings: W1, inci: 'Alcohol denat., Parfum, Hexamethylindanopyran, Linalyl acetate, Tetramethyl acetyloctahydronaphthalenes, Hydroxycitronellal, Limonene, Alpha-isomethyl ionone, Geraniol, Citronellol, Acetylcedrene, Hexyl cinnamal, Linalool, Vanillin, Amyl salicylate, Pogostemon cablin oil, Geranyl acetate, Pinene, Rose ketones, Beta-caryophyllene, Citral, Benzaldehyde' },
  '152M': { paoMonths: 36, warnings: W1, inci: 'Alcohol denat., Parfum, Tetramethyl acetyloctahydronaphthalenes, Linalyl acetate, Limonene, Linalool, Citrus aurantium peel oil, Citrus limon peel oil, Hexamethylindanopyran, Pogostemon cablin oil, Pinene, Lavandula oil/extract, Amyl salicylate, Alpha-isomethyl ionone, Beta-caryophyllene, Benzyl salicylate, Trimethylcyclopentenyl methylisopentenol, Vanillin, Citral, Camphor, Terpineol, Geranyl acetate, Geraniol, Rose ketones, Terpinolene, Citronellol, Alpha-terpinene, Eugenol, Carvone, Farnesol' },
  '061M': { paoMonths: 36, warnings: W1, inci: 'Alcohol denat., Parfum, Tetramethyl acetyloctahydronaphthalenes, Benzyl benzoate, Hexamethylindanopyran, Limonene, Linalool, Linalyl acetate, Coumarin, Citrus limon peel oil, Citronellol, Geraniol, Amyl benzoate, Alpha-isomethyl ionone, Pinene, Methyl benzoate, Vanillin, Cinnamomum zeylanicum bark oil, Cinnamal, Isoeugenyl acetate, Hydroxycitronellal, Citral, Rose ketones, Mentha piperita oil, Mentha viridis leaf oil, Carvone, Menthol, Benzyl alcohol, Beta-caryophyllene, Terpinolene, Evernia extract, Terpineol, Eugenol, Juniperus virginiana oil, Alpha-terpinene, Geranyl acetate' },
  '155U': { paoMonths: 36, warnings: W3, inci: 'Alcohol denat., Parfum, Hexamethylindanopyran, Linalyl acetate, Citrus limon peel oil, Linalool, Limonene, Tetramethyl acetyloctahydronaphthalenes, Pinene, Citronellol, Citral, Geranyl acetate, Coumarin, Geraniol, Pogostemon cablin oil, Vanillin, Beta-caryophyllene, Benzyl alcohol, Terpineol' },
  '150M': { paoMonths: 36, warnings: W2, inci: 'Alcohol denat., Parfum, Hexamethylindanopyran, Tetramethyl acetyloctahydronaphthalenes, Linalyl acetate, Limonene, Benzyl salicylate, Linalool, Amyl salicylate, Acetylcedrene, Pogostemon cablin oil, Citrus aurantium peel oil, Citrus limon peel oil, Trimethylcyclopentenyl methylisopentenol, Eugenia caryophyllus leaf oil, Lavandula angustifolia extract, Hydroxycitronellal, Eugenol, Pinene, Beta-caryophyllene, Lavandula angustifolia extract, Pelargonium graveolens flower oil, Juniperus virginiana oil, Citral, Citronellol, Geraniol, Eugenyl acetate, Camphor, Benzyl benzoate, Geranyl acetate, Terpineol, Terpinolene' },
  '156W': { paoMonths: 36, warnings: W1, inci: 'Alcohol denat., Parfum, Benzyl salicylate, Hexamethylindanopyran, Alpha-isomethyl ionone, Tetramethyl acetyloctahydronaphthalenes, Benzyl benzoate, Hexyl cinnamal, Citronellol, Hydroxycitronellal, Linalool, Isoeugenyl acetate, Isoeugenol, Linalyl acetate, Terpineol, Citrus limon peel oil, Limonene, Citral, Eugenol' },
  '164M': { paoMonths: 36, warnings: 'Nie spryskiwać na otwarty ogień ani na rozgrzane powierzchnie; Unikać kontaktu z oczami; Trzymać z dala od dzieci', inci: 'Alcohol denat., Parfum, Tetramethyl acetyloctahydronaphthalenes, Vanillin, Coumarin, Linalyl acetate, Santalum album oil, Citronellol, Linalool, Limonene, Pelargonium graveolens flower oil, Santalol, Lavandula oil/extract, Myroxylon balsamum pereirae balsam oil, Citrus aurantium peel oil, Geraniol, Alpha-isomethyl ionone, Benzyl benzoate, Trimethylcyclopentenyl methylisopentenol, Pinene, Geranyl acetate, Benzyl cinnamate, Eucalyptus globulus leaf/twig oil, Citral, Rose ketones, Cinnamomum zeylanicum bark oil, Cinnamal, Anethole, Eugenol, Camphor, Farnesol, Beta-caryophyllene, Eugenyl acetate' },
  '053W': { paoMonths: 36, warnings: W1, inci: 'Alcohol denat., Parfum, Tetramethyl acetyloctahydronaphthalenes, Acetylcedrene, Hexamethylindanopyran, Juniperus virginiana oil, Trimethylbenzenepropanol, Pogostemon cablin oil, Vanillin, Citrus limon peel oil, Linalyl acetate, Limonene, Dimethylbenzyl carbinyl acetate, Linalool, Citronellol, Alpha-isomethyl ionone, Cedrus atlantica oil/extract, Hexyl cinnamal, Citrus aurantium peel oil, Pinene, Geraniol, Benzyl benzoate, Hydroxycitronellal, Isoeugenyl acetate, Cinnamyl alcohol, Benzyl salicylate, Beta-caryophyllene, Rose ketones, Citral, Geranyl acetate, Pelargonium graveolens flower oil, Terpinolene, Eugenol, Alpha-terpinene' },
  '067W': { paoMonths: 36, warnings: W3, inci: 'Alcohol denat., Parfum, Hexamethylindanopyran, Benzyl salicylate, Vanillin, Citronellol, Tetramethyl acetyloctahydronaphthalenes, Citrus aurantium peel oil, Limonene, Linalool, Coumarin, Trimethylbenzenepropanol, Amyl salicylate, Cinnamyl alcohol, Alpha-isomethyl ionone, Isoeugenyl acetate, Geranyl acetate, Geraniol, Rose ketones, Terpineol, Citral, Pinene, Benzyl alcohol, Linalyl acetate, Cinnamal' },
  '122W': { paoMonths: 36, warnings: W1, inci: 'Alcohol denat., Parfum, Tetramethyl acetyloctahydronaphthalenes, Limonene, Linalyl acetate, Vanillin, Linalool, Citrus aurantium peel oil, Benzyl salicylate, Hexamethylindanopyran, Citrus limon peel oil, Acetylcedrene, Hydroxycitronellal, Coumarin, Pinene, Citronellol, Geranyl acetate, Geraniol, Citral, Pogostemon cablin oil, Isoeugenyl acetate, Lavandula oil/extract, Rose ketones, Terpineol, Beta-caryophyllene, Terpinolene' },
  '158W': { paoMonths: 36, warnings: W1, inci: 'Alcohol denat., Parfum, Tetramethyl acetyloctahydronaphthalenes, Limonene, Benzyl salicylate, Hydroxycitronellal, Linalyl acetate, Linalool, Alpha-isomethyl ionone, Citrus aurantium peel oil, Citrus limon peel oil, Juniperus virginiana oil, Hexyl cinnamal, Isoeugenyl acetate, Pinene, Geraniol, Citronellol, Hexadecanolactone, Geranyl acetate, Citral, Rose ketones, Terpineol, Beta-caryophyllene, Benzyl alcohol, Carvone' },
  '026W': { paoMonths: 36, warnings: 'Nie spryskiwać na inne źródła zapłonu; Unikać kontaktu z oczami; Trzymać z dala od dzieci', inci: 'Alcohol denat., Parfum, Tetramethyl acetyloctahydronaphthalenes, Hexamethylindanopyran, Geraniol, Hydroxycitronellal, Citronellol, Vanillin, Linalool, Linalyl acetate, Alpha-isomethyl ionone, Limonene, Terpineol, Pinene, Beta-caryophyllene, Benzyl benzoate, Citral, Geranyl acetate, Benzaldehyde, Benzyl alcohol, Citrus limon peel oil, Terpinolene, Sclareol, Benzyl salicylate, Eugenol' },
  '087M': { paoMonths: 36, warnings: W1, inci: 'Alcohol denat., Parfum, Tetramethyl acetyloctahydronaphthalenes, Pogostemon cablin oil, Benzyl salicylate, Citrus limon peel oil, Linalyl acetate, Citronellol, Limonene, Coumarin, Pinene, Linalool, Amyl salicylate, Geraniol, Beta-caryophyllene, Acetylcedrene, Vanillin, Eugenol, Citral, Rose ketones, Anethole, Alpha-terpinene, Camphor' },
  // Pages 71-90 luxury products
  '113M': { paoMonths: 36, warnings: W1, inci: 'Alcohol denat., Parfum, Linalyl acetate, Limonene, Pogostemon cablin oil, Citrus limon peel oil, Linalool, Pinene, Citral, Myroxylon pereirae oil, Citrus aurantium peel oil, Beta-caryophyllene, Benzyl benzoate, Sclareol, Cinnamomum zeylanicum bark oil, Benzyl cinnamate, Terpineol, Cinnamal, Camphor, Geraniol, Geranyl acetate, Terpinolene, Carvone, Mentha viridis oil, Alpha-terpinene, Citronellol, Eugenol, Farnesol' },
  '127U': { paoMonths: 36, warnings: W1, inci: 'Alcohol denat., Parfum, Tetramethyl acetyloctahydronaphthalenes, Pogostemon cablin oil, Linalool, Hexamethylindanopyran, Geraniol, Beta-caryophyllene, Coumarin, Vanillin, Limonene, Citrus limon peel oil, Camphor, Geranyl acetate, Terpineol, Linalyl acetate' },
  'ASTRAL24': { paoMonths: 36, warnings: W2, inci: 'Alcohol denat., Parfum, Tetramethyl acetyloctahydronaphthalenes, Citrus limon peel oil, Linalyl acetate, Limonene, Linalool, Benzyl benzoate, Rose ketone, Citronellol, Citral, Terpineol, Geranyl acetate, Beta-caryophyllene, Geraniol, Benzyl alcohol' },
  '129U': { paoMonths: 36, warnings: 'Nie spryskiwać na inne źródła zapłonu; Unikać kontaktu z oczami; Trzymać z dala od dzieci', inci: 'Alcohol denat., Parfum, Tetramethyl acetyloctahydronaphthalenes, Hexamethylindanopyran, Limonene, Linalyl acetate, Hexyl cinnamal, Benzyl salicylate, Citrus aurantium peel oil, Citrus limon peel oil, Alpha-isomethyl ionone, Linalool, Hydroxycitronellal, Dimethylbenzyl carbinyl acetate, Trimethylcyclopentenyl methylisopentenol, Geraniol, Geranyl acetate, Pogostemon cablin oil, Isoeugenyl acetate, Citral, Beta-caryophyllene, Anise alcohol, Terpinolene' },
  '144U': { paoMonths: 36, warnings: 'Nie spryskiwać na otwarty ogień ani rozgrzane powierzchnie; Unikać kontaktu z oczami; Trzymać poza zasięgiem dzieci; Ważne: Nie spryskiwać bezpośrednio na tkaniny, aby uniknąć plam na odzieży', inci: 'Alcohol denat., Parfum, Hexamethylindanopyran, Coumarin' },
  '74M': { paoMonths: 36, warnings: W1, inci: 'Alcohol denat., Parfum, Tetramethyl acetyloctahydronaphthalenes, Juniperus virginiana oil, Trimethylcyclopentenyl methylisopentenol, Alpha-isomethyl ionone, Pogostemon cablin oil, Vanillin, Hexadecanolactone, Acetylcedrene, Coumarin, Isoeugenyl acetate, Beta-caryophyllene, Benzaldehyde, Myroxylon pereirae oil, Linalool, Pelargonium graveolens flower oil, Limonene, Hexamethylindanopyran, Benzyl benzoate' },
  '124U': { paoMonths: 36, warnings: W1, inci: 'Alcohol denat., Parfum, Tetramethyl acetyloctahydronaphthalenes, Limonene, Hexamethylindanopyran, Linalyl acetate, Citrus limon peel oil, Coumarin, Linalool, Pinene' },
  'IMPERATRIX': { paoMonths: 36, warnings: 'Nie spryskiwać na otwarty ogień ani na rozgrzane powierzchnie; Unikać kontaktu z oczami; Trzymać z dala od dzieci', inci: 'Alcohol denat., Parfum, Tetramethyl acetyloctahydronaphthalenes, Hexamethylindanopyran, Alpha-isomethyl ionone, Hydroxycitronellal, Citrus aurantium peel oil, Limonene, Hexyl cinnamal, Benzyl benzoate, Citronellol, Linalool, Dimethylbenzyl carbinyl acetate, Vanillin, Evernia prunastri (oakmoss) extract, Rose flower oil/extract, Pinene, Isoeugenyl acetate, Beta-caryophyllene, Rose ketones, Geraniol, Terpinolene, Benzaldehyde, Benzyl alcohol, Cananga odorata oil/extract, Juniperus virginiana oil, Farnesol, Citral, Terpineol, Eugenol' },
  'MULTIVERSE': { paoMonths: 36, warnings: W2, inci: 'Alcohol denat., Parfum, Vanillin, Hexamethylindanopyran, Linalyl acetate, Citrus limon peel oil, Limonene, Linalool, Farnesol, Rose ketone, Benzyl benzoate, Citral, Cinnamomum zeylanicum bark oil, Cinnamic aldehyde/cinnamaldehyde, Geraniol, Terpineol, Citrus aurantium dulcis peel oil, Eugenol, Geranyl acetate, Benzyl cinnamate, Beta-caryophyllene' },
  'EVENT23M': { paoMonths: 36, warnings: W1, inci: 'Alcohol denat., Parfum, Hexyl cinnamal, Alpha-isomethyl ionone, Linalool, Hydroxycitronellal, Eugenol, Benzyl salicylate, Citronellol, Limonene, Coumarin, Geraniol, Citral' },
  'NADIR': { paoMonths: 36, warnings: W2, inci: 'Alcohol denat., Parfum, Linalyl acetate, Tetramethyl acetyloctahydronaphthalenes, Citrus limon peel oil, Linalool, Limonene, Citronellol, Pinene, Vanillin, Coumarin, Citral, Hydroxycitronellal, Rose ketones, Geraniol, Terpineol, Beta-caryophyllene, Camphor, Terpinolene, Geranyl acetate, Alpha-terpinene' },
  '130U': { paoMonths: 36, warnings: W1, inci: 'Alcohol denat., Parfum, Benzyl benzoate, Citronellol, Citrus limon peel oil, Limonene, Trimethylcyclopentenyl methylisopentenol, Pogostemon cablin oil, Geraniol, Alpha-isomethyl ionone, Vanillin, Pinene, Citrus aurantium bergamia peel oil, Rose ketones, Geranyl acetate, Linalool, Linalyl acetate, Citral, Beta-caryophyllene' },
  '75': { paoMonths: 36, warnings: W2, inci: 'Alcohol denat, Parfum, Limonene, Linalool, Eugenol, Evernia prunastri extract, Geraniol, Cinnamal, Cinnamyl alcohol, Citral, Coumarin, Benzyl cinnamate, Farnesol, Benzyl alcohol' },
  '102': { paoMonths: 36, warnings: W2, inci: 'Alcohol denat, Parfum, Farnesol, Linalool, Coumarin, Limonene, Benzyl benzoate, Cinnamal, Geraniol, Benzyl cinnamate, Citronellol, Anise alcohol' },
  '125': { paoMonths: 36, warnings: W2, inci: 'Alcohol denat, Parfum, Limonene, Linalool, Alpha-isomethyl ionone, Hydroxycitronellal, Farnesol, Citral, Geraniol, Eugenol, Citronellol' },
  '126U': { paoMonths: 36, warnings: W1, inci: 'Alcohol denat., Parfum, Benzyl salicylate, Hexamethylindanopyran, Linalyl acetate, Limonene, Linalool, Citrus limon peel oil, Vanillin, Citrus aurantium peel oil, Pinene, Coumarin, Citral, Benzyl benzoate, Cananga odorata oil/extract, Benzaldehyde, Beta-caryophyllene, Terpineol, Benzyl alcohol, Benzyl cinnamate, Terpinolene, Geraniol, Farnesol' },
  '139': { paoMonths: 36, warnings: W2, inci: 'Alcohol denat., Parfum, Citronellol, Tetramethyl acetyloctahydronaphthalenes, Benzyl salicylate, Alpha-hexyl cinnamic aldehyde, Acetylcedrene, Geranyl acetate, Geraniol, Linalool, Pogostemon cablin oil, Vanillin, Hydroxycitronellal, Limonene, Linalyl acetate, Rose ketones, Dimethyl phenethyl acetate, Beta-caryophyllene, Eugenol' },
  '134': { paoMonths: 36, warnings: W2, inci: 'Alcohol denat, Parfum, Linalool, Limonene, Coumarin, Benzyl benzoate, Benzyl cinnamate, Alpha-isomethyl ionone, Citral, Geraniol, Benzyl alcohol, Citronellol, Amyl cinnamal, Cinnamal, Eugenol, Cinnamyl alcohol, Benzyl salicylate, Farnesol, Hexyl cinnamal, Evernia furfuracea extract, Isoeugenol' },
  '112': { paoMonths: 36, warnings: W2, inci: 'Alcohol denat, Parfum, Limonene, Linalool, Geraniol, Citral, Citronellol, Hydroxycitronellal, Eugenol, Farnesol' },
  '106': { paoMonths: 36, warnings: W2, inci: 'Alcohol denat, Parfum, Limonene, Coumarin, Linalool, Hexyl cinnamal, Citronellol, Citral, Alpha-isomethyl ionone, Geraniol, Benzyl cinnamate, Benzyl benzoate' },
  '138': { paoMonths: 36, warnings: W2, inci: 'Alcohol denat, Parfum, Benzyl benzoate, Coumarin, Limonene, Citronellol, Isoeugenol, Linalool, Benzyl cinnamate, Citral' },
  '109W': { paoMonths: 36, warnings: W1, inci: 'Alcohol denat., Parfum, Tetramethyl acetyloctahydronaphthalenes, Alpha-isomethyl ionone, Linalool, Citronellol, Hydroxycitronellal, Trimethylcyclopentenyl methylisopentenol, Juniperus virginiana oil, Coumarin, Cananga odorata oil/extract, Limonene, Geraniol, Benzyl benzoate, Beta-caryophyllene, Pinene, Citrus aurantium peel oil, Cedrus atlantica oil/extract, Pogostemon cablin oil, Geranyl acetate, Benzyl salicylate, Rose ketones, Farnesol, Citral, Isoeugenol, Rose flower oil/extract, Eugenol, Linalyl acetate, Terpinolene, Benzyl alcohol, Benzaldehyde' },
  '111U': { paoMonths: 36, warnings: W1, inci: 'Alcohol denat., Parfum, Vanillin, Coumarin, Benzaldehyde, Trimethylcyclopentenyl methylisopentenol, Myroxylon balsamum pereirae balsam oil, Benzyl benzoate, Anisyl alcohol, Rose ketones, Isoeugenol, Citronellol, Cinnamomum zeylanicum bark oil, Cinnamal, Benzyl alcohol, Geraniol, Linalool, Eugenol, Cananga odorata flower oil, Eugenyl acetate, Beta-caryophyllene' },
  '141U': { paoMonths: 36, warnings: 'Nie spryskiwać na inne źródła zapłonu; Unikać kontaktu z oczami; Przechowywać w miejscu niedostępnym dla dzieci', inci: 'Alcohol denat., Parfum, Tetramethyl acetyloctahydronaphthalenes, Pogostemon cablin oil, Benzyl benzoate, Cedrus atlantica wood oil, Acetylcedrene, Citrus aurantium peel oil, Myroxylon pereirae oil/extract, Limonene, Linalool, Trimethylcyclopentenyl methylisopentenol, Benzyl alcohol, Hexyl cinnamal, Linalyl acetate, Alpha-isomethyl ionone, Hexamethylindanopyran, Vanillin, Citronellol, Hydroxycitronellal, Juniperus virginiana oil, Eugenol, Rose ketones, Pinene' },
  '118U': { paoMonths: 36, warnings: W1, inci: 'Alcohol denat., Parfum, Tetramethyl acetyloctahydronaphthalenes, Limonene' },
  '146U': { paoMonths: 36, warnings: W2, inci: 'Alcohol denat., Parfum, Tetramethyl acetyloctahydronaphthalenes, Hydroxycitronellal, Acetylcedrene, Linalool, Eugenol, Citrus aurantium peel oil, Limonene, Cananga odorata flower oil, Rose ketones, Cinnamomum zeylanicum bark oil, Cinnamal, Hexadecanolactone, Benzyl benzoate, Benzyl alcohol, Beta-caryophyllene, Pinene, Geranyl acetate, Farnesol, Terpineol, Benzyl salicylate' },
  '137U': { paoMonths: 36, warnings: W1, inci: 'Alcohol denat., Parfum, Tetramethyl acetyloctahydronaphthalenes, Linalool, Pogostemon cablin oil, Vanillin, Citrus limon peel oil, Coumarin, Limonene, Benzyl salicylate, Linalyl acetate, Juniperus virginiana oil, Lavandula oil/extract, Sclareol, Pinene, Citronellol, Cinnamomum zeylanicum bark oil, Pelargonium graveolens flower oil, Beta-caryophyllene, Cinnamal, Menthol, Rose ketones, Citral, Alpha-isomethyl ionone, Citrus aurantium peel oil, Geraniol, Terpineol, Anethole, Hydroxycitronellal, Alpha-terpinene, Benzyl benzoate, Benzyl alcohol, Terpinolene, Cananga odorata oil/extract, Mentha piperita oil, Camphor, Eugenol, Farnesol' },
  '101U': { paoMonths: 36, warnings: W1, inci: 'Alcohol denat., Parfum, Tetramethyl acetyloctahydronaphthalenes, Linalool, Pogostemon cablin oil, Vanillin, Citrus limon peel oil, Coumarin, Limonene, Benzyl salicylate, Linalyl acetate, Juniperus virginiana oil, Lavandula oil/extract, Sclareol, Pinene, Citronellol, Cinnamomum zeylanicum bark oil, Pelargonium graveolens flower oil, Beta-caryophyllene, Cinnamal, Menthol, Rose ketones, Citral, Alpha-isomethyl ionone, Citrus aurantium peel oil, Geraniol, Terpineol, Anethole, Hydroxycitronellal, Alpha-terpinene, Benzyl benzoate, Benzyl alcohol, Terpinolene, Cananga odorata oil/extract, Mentha piperita oil, Camphor, Eugenol, Farnesol' },
  // 30ml-only variant from INCI pages (code 096W = 30ml only product "The Muse")
  '096W': { paoMonths: 36, warnings: W3, inci: 'Alcohol denat., Parfum, Hexyl cinnamal, Linalyl acetate, Limonene, Citronellol, Citrus limon peel oil, Geraniol, Linalool, Benzyl salicylate, Pinene, Cananga odorata flower oil, Citrus aurantium peel oil, Santalum album oil, Acetylcedrene, Santalol, Benzyl benzoate, Hydroxycitronellal, Vanillin, Geranyl acetate, Rose ketones, Citral, Coumarin, Benzyl alcohol, Eugenol, Beta-caryophyllene, Benzyl cinnamate, Farnesol, Terpinolene' },
  '086M': { paoMonths: 36, warnings: W1, inci: 'Alcohol denat., Parfum, Tetramethyl acetyloctahydronaphthalenes, Acetylcedrene, Linalyl acetate, Citronellol, Linalool, Citrus limon peel oil, Limonene, Coumarin, Eucalyptus globulus oil, Trimethylcyclopentenyl methylisopentenol, Sclareol, Pinene, Lavandula oil/extract, Rose ketones, Citral, Geraniol, Camphor, Geranyl acetate, Terpineol, Beta-caryophyllene' },
};

// ─── SDS file mapping: base_code → PDF filename ──────────────────────────────

const SDS_FILES: Record<string, string> = {
  'COP0001': 'sds_1_COP0001_1665585659.pdf',
  'COP0006': 'sds_1_COP0006_1665644975.pdf',
  'COP0011': 'sds_3_COP0011_1732549516.pdf',
  'COP0016': 'sds_1_COP0016_1732549518.pdf',
  'COP0021': 'sds_1_COP0021_1732549521.pdf',
  'COP0026': 'sds_1_COP0026_1732549522.pdf',
  'COP0031': 'sds_1_COP0031_1760712654.pdf',
  'COP0034': 'sds_1_COP0034_1760712653.pdf',
  'COP0037': 'sds_1_COP0037_1762851127.pdf',
  'COP0040': 'sds_1_COP0040_1760712737.pdf',
  'COP0043': 'sds_1_COP0043_1760712739.pdf',
  'COP0046': 'sds_1_COP0046_1760712806.pdf',
};

// ─── Main ─────────────────────────────────────────────────────────────────────

async function main() {
  let complianceUpdated = 0;
  let complianceSkipped = 0;

  console.log('Updating compliance data (ingredients, warnings, PAO)...');

  for (const [baseCode, data] of Object.entries(COMPLIANCE)) {
    // Find product whose primary variant SKU = base_code
    const product = await prisma.product.findFirst({
      where: { variants: { some: { sku: baseCode } } },
      select: { id: true, name: true },
    });

    if (!product) {
      console.warn(`  SKIP: no product found for code ${baseCode}`);
      complianceSkipped++;
      continue;
    }

    await prisma.product.update({
      where: { id: product.id },
      data: {
        ingredients: data.inci,
        warnings: data.warnings,
        paoMonths: data.paoMonths,
      },
    });

    complianceUpdated++;
    console.log(`  ✓ ${baseCode} → ${product.name}`);
  }

  console.log(`\nCompliance: ${complianceUpdated} updated, ${complianceSkipped} skipped\n`);

  // ── Upload SDS PDFs and set sdsUrl on diffuser products ──────────────────

  console.log('Uploading SDS PDFs to Supabase...');
  let sdsUpdated = 0;

  for (const [baseCode, filename] of Object.entries(SDS_FILES)) {
    const filePath = path.join(DOCS_DIR, filename);

    if (!fs.existsSync(filePath)) {
      console.warn(`  SKIP: SDS file not found at ${filePath}`);
      continue;
    }

    const product = await prisma.product.findFirst({
      where: { variants: { some: { sku: baseCode } } },
      select: { id: true, name: true },
    });

    if (!product) {
      console.warn(`  SKIP: no product found for diffuser code ${baseCode}`);
      continue;
    }

    const buffer = fs.readFileSync(filePath);
    const storagePath = `sds/${filename}`;

    const { error } = await supabase.storage
      .from(SDS_BUCKET)
      .upload(storagePath, buffer, { contentType: 'application/pdf', upsert: true });

    if (error) {
      console.error(`  ERROR uploading SDS for ${baseCode}:`, error.message);
      continue;
    }

    const { data: urlData } = supabase.storage
      .from(SDS_BUCKET)
      .getPublicUrl(storagePath);

    await prisma.product.update({
      where: { id: product.id },
      data: { sdsUrl: urlData.publicUrl },
    });

    sdsUpdated++;
    console.log(`  ✓ ${baseCode} (${product.name}) → ${urlData.publicUrl}`);
  }

  console.log(`\nSDS: ${sdsUpdated} uploaded and linked\n`);
  console.log('Done!');
}

main()
  .catch((err) => { console.error(err); process.exit(1); })
  .finally(() => prisma.$disconnect());
