-- Supabase Storage — invoices bucket setup
--
-- Apply via Supabase Dashboard → SQL Editor. Idempotent: safe to re-run.
--
-- Security model:
--   Invoice PDFs contain full name, street address, NIP (tax ID), all order
--   items, and price paid. They must NEVER be publicly readable.
--
--   Reads: the bucket is private (public = false). All read access goes through
--   GET /orders/:id/invoice on the backend, which:
--     1. Verifies order.userId === req.user.id
--     2. Issues a short-lived signed URL (1 h) via storage.createSignedUrl()
--   Signed URLs are generated by the service-role key which bypasses RLS, so
--   no explicit SELECT policy is needed for authenticated users.
--
--   Writes: the backend uses SUPABASE_SERVICE_ROLE_KEY which bypasses RLS.
--   No INSERT/UPDATE policy is needed.
--
--   anon / authenticated writes: Supabase's default is deny-unless-permitted.
--   We create no permissive policies, so anon and authenticated clients have
--   no write access. Belt-and-braces policy below makes this explicit.
--
-- Note on CREATE POLICY ownership errors:
--   Newer Supabase projects lock ownership of storage.objects so CREATE POLICY
--   from the SQL editor may fail with "must be owner of table objects".
--   If that happens, add the deny policy via Dashboard UI:
--     Storage → Policies → invoices bucket → New policy →
--     For SELECT/INSERT/UPDATE/DELETE, target roles anon + authenticated,
--     USING expression: false

-- Ensure the bucket exists and is marked private (no CDN reads).
insert into storage.buckets (id, name, public)
values ('invoices', 'invoices', false)
on conflict (id) do update set public = false;

-- Deny all public reads — belt-and-braces in case the bucket is ever
-- accidentally flipped to public = true.
-- Signed URLs issued by the service-role backend bypass RLS, so this
-- policy does not block legitimate invoice downloads.
create policy "no public reads on invoices"
  on storage.objects
  for select
  using (bucket_id = 'invoices' and false);
